three-rs/three

Cargo.toml
examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/shapes.rs
src/camera.rs
src/factory.rs
src/lib.rs
src/render.rs
src/scene.rs

Fixes #4 
It's rough around the edges because cgmath-rs hasn't got `mint` support yet

Mint flavour integration

---

examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/shapes.rs
examples/sprite.rs
src/factory.rs
src/lib.rs
src/render.rs
src/scene.rs

Local state removal

---

Cargo.toml
examples/aviator/sky.rs
examples/group.rs
src/factory.rs
src/lib.rs
src/scene.rs

Runs quite slow on my machine with 6 levels, presumably because we don't cache the current pipeline, so it's a good testcase.

Cube-ception (group) demo

---

examples/obj.rs
src/camera.rs
src/input.rs
src/lib.rs
src/window.rs

Fixes #13
Not tested that much, but works on the `obj` sample
r? @vitvakatu

OrbitControls

---

src/input.rs
src/window.rs

Add mouse wheel input handling

---

examples/anim.rs
examples/aviator/main.rs
examples/group.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/shapes.rs
examples/sprite.rs
src/camera.rs
src/window.rs

Builder patterns for `OrbitControls` and `Window`.

Builder patterns

---

src/input.rs

Expose mouse_moves

---

Cargo.toml
src/render.rs
src/window.rs

Update to glutin 0.9

---

src/factory.rs
src/lib.rs
src/render.rs

Adds the blend & stencil states to custom pipelines.

Moare custom pipeline states

---

src/camera.rs

This completes https://github.com/kvark/three-rs/pull/59

Add mouse wheel zooming to OrbitControls

---

examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/group.rs
examples/shapes.rs
src/camera.rs
src/input.rs
src/lib.rs
src/scene.rs

Closes #65 
I hope I didn't miss anything.

Remove temporal cgmath <-> mint conversions.

---

src/lib.rs

This PR documents the mesh duplication process more clearly.

Add examples for Mesh

---

Cargo.toml
src/hub.rs
src/render.rs

I checked `group` example - it works as desired.

Update to froggy v0.4

---

Cargo.toml

https://github.com/alexheretic/gfx-glyph/issues/2

Fix TODO (gfx_glyph has been updated)

---

src/render.rs
src/scene.rs

Add textured background

---

Cargo.toml
examples/tutorial.rs
src/camera.rs
src/controls/mod.rs
src/custom.rs
src/input.rs
src/lib.rs
src/macros.rs
src/text.rs

This PR intends to document the whole project more thoroughly.

Add more documentation

---

src/controls/first_person.rs
src/window.rs

Expose underlaying glutin::GlWindow

---

Cargo.toml
examples/mesh-update.rs
src/factory/mod.rs
src/lib.rs
src/mesh.rs
src/render.rs

This PR allows the user to alter the vertices of a `DynamicMesh` at runtime.

Allow user to update positions of DynamicMesh

---

.travis.yml
README.md

Readme improvements

---

src/input/mod.rs

Useful for implementing text input in user code.

Add Input::keys_hit

---

examples/anim.rs
examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/gltf-animation.rs
examples/gltf.rs
examples/group.rs
examples/lights.rs
examples/materials.rs
examples/mesh-update.rs
examples/obj.rs
examples/reload.rs
examples/shapes.rs
examples/sprite.rs
examples/tutorial.rs
src/animation.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/hub.rs
src/lib.rs
src/node.rs
src/object.rs
src/render/mod.rs
src/scene.rs

This PR addresses #44, implementing the `set_parent` idea.

Implement Object::set_parent

---

Cargo.toml
src/object.rs

Use old include rules

---

src/render/mod.rs

Rename get_aspect as aspect_ratio

---

src/lib.rs
src/node.rs
src/object.rs
src/scene.rs

Implement SyncGuard

---

Cargo.toml
src/factory/mod.rs
src/render/mod.rs
src/render/pso_data.rs
src/window.rs

Notably, gfx-0.17 and obj-0.8 are here

Depenency updates and cleanups

---

.travis.yml
Cargo.toml
src/animation.rs
src/factory/mod.rs
src/lib.rs

Add gltf-loader feature

---

examples/anim.rs
examples/aviator/main.rs
examples/group.rs
examples/mesh-update.rs
examples/sprite.rs
src/input/mod.rs
src/input/timer.rs

Make Timer independent

---

examples/obj.rs
src/controls/orbit.rs
src/input/mod.rs

Aaaand again. Now the problem has been spotted in `gltf` example.
UPD: closes #180

Fix timed method in Delta implementation for axis::Key

---

Cargo.toml
build.rs
src/factory/mod.rs
src/render/mod.rs

Fixes #192
TODO: instanced tile map example (in follow-ups)

Instanced sprites entry point

---

Cargo.toml
src/animation.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/lib.rs

Courtesy PR for updating to the new version of the gltf crate.

Update to gltf version 0.11

---

Cargo.toml
src/factory/load_gltf.rs
src/factory/mod.rs

In the process bumped both gltf and image deps

Fix gltf build
