examples/aviator.rs
examples/box.rs
examples/line.rs
examples/sprite.rs
src/camera.rs
src/factory.rs
src/lib.rs
src/render.rs
src/scene.rs
src/window.rs

This PR makes the engine to keep a single scenegraph with fat nodes, instead of separate little storage-graphics per scene. It's designed to improve ergonomics.
Fixes #6

Scene graph re-architecture

---

src/factory.rs
src/lib.rs
src/render.rs
src/scene.rs
src/window.rs

[WIP] Documentation

---

src/scene.rs

I think it was mistake not to call `update_graph` in `sync()`.
Without this, `NodeInfo` doesn't contain *actual* info and `sync()` panics on `scene_id` assertion.

Update graph in sync

---

Cargo.toml
examples/aviator/main.rs
examples/aviator/plane.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/shapes.rs
examples/sprite.rs
src/input.rs
src/lib.rs
src/render.rs
src/window.rs

New input API

---

.travis.yml
examples/aviator/main.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/shapes.rs
examples/sprite.rs
src/camera.rs
src/factory.rs
src/lib.rs
src/render.rs
src/scene.rs
src/window.rs

Finishes the last bits of #4
Also simplifies the projection setups.
Basically, we only provide the vertical FOV/extent, and the horizontal is derived from the current aspect ratio in order to produce square pixels.

Native projection types

---

src/lib.rs
src/macros.rs

This macro makes it really easy for structs that simply wrap a three-rs type to implement the right traits so that those custom types can interop with three-rs methods really easily.
The macro is nice and flexible and the field name is optional. I chose the syntax `MyStruct#field` because it seemed more natural to me than `MyStruct.field` or `MyStruct::field` (since `x::y` is usually for modules or methods, not fields).
[See the effect of this change here](https://github.com/sunjay/panda/commit/d508806d9f5f47fe4267b98f5823142108decaac)
Really wanted to replace macros in `src/scene.rs` with some macros that could be used outside of the crate, but unfortunately that didn't workout because while internal three objects have access to the `node` field, structs external to the crate do not. …

Added macro for implementing conversion traits on structs that wrap three-rs types.

---

src/render.rs

Fixes crashes on Windows machines when trying to minimize application

Check window sizes before updating the view

---

data/shaders/pbr_ps.glsl

The deprecated function caused a shader compiler error on macOS.
Edit:
fixes #63

PBR shader: replace deprecated texture2D with texture (#63)

---

examples/anim.rs
examples/aviator/main.rs
examples/group.rs
examples/lights.rs
examples/materials.rs
examples/obj.rs
examples/pbr.rs
examples/shapes.rs
examples/sprite.rs

Now you can call "cargo run --example <example name>" from any directory,
not only from the root "Cargo.toml" directory.

Make it possible to run examples from anywhere in the source tree

---

src/factory.rs
test_data/texture.mtl

When loading textures referenced in a MTL file, load them relative to the location of the MTL file, not the current working directory.

Make paths in mtl files relative

---

Cargo.toml

`winit 0.6.4` depends on the slightly outdated `cocoa 0.5.2`, which can't be compiled with nightly on Mac (56 x ```error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied```).

Update winit to 0.7.5 to fix compilation on Mac (nightly)

---

examples/aviator/sky.rs
examples/group.rs
src/factory.rs
src/lib.rs

There might be a more idiomatic way of providing this functionality. Would it be better to provide a `Mesh::material()` function instead?

Allow mesh instances to duplicate their materials

---

data/shaders/globals.glsl
data/shaders/lights.glsl
data/shaders/pbr_ps.glsl
data/shaders/quad_vs.glsl

This PR adds standardises the layout of uniform blocks with `layout(std140)` to prevent hardware-dependent data alignment/padding issues. Fixes https://github.com/three-rs/three/issues/93.

Use layout(std140)

---

examples/aviator/main.rs
examples/aviator/plane.rs
examples/lights.rs
examples/shapes.rs
examples/sprite.rs
src/audio.rs
src/camera.rs
src/controls/first_person.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/geometry.rs
src/hub.rs
src/input.rs
src/render.rs
src/text.rs
src/texture.rs
src/window.rs

Adds runnable code examples to the geometry module documentation.
This also renames `Geometry::sphere` as `Geometry::uv_sphere` to make way for icosahedral spheres.

Add examples in geometry documentation

---

src/render.rs

Closes #104 
Doesn't affect anything due to bug in gfx, but this hotfix should be replaced with appropriate off-screen render target (see #109)
The reason I pushed this is that I can't work on `three-rs` because of this bug.

Color format hotfix

---

examples/anim.rs
examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/group.rs
examples/lights.rs
examples/materials.rs
examples/mesh-update.rs
examples/reload.rs
examples/shapes.rs
examples/sprite.rs
examples/tutorial.rs
src/animation.rs
src/color.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/hub.rs
src/lib.rs
src/material.rs
src/mesh.rs
src/render/mod.rs
src/render/source.rs
src/scene.rs
src/text.rs
src/util.rs

In response to #105 , this PR changes the way materials are specified.
* There are explicit data structures for each of the pipelines.
~~* The `LineBasic` material and its implementation has been removed.~~
~~* Hence, only mesh materials will be supported.~~
* There are explicit pipelines `Basic`, `basic::Custom`, and `Wireframe`.

New material strategy

---

src/camera.rs
src/controls/orbit.rs
src/hub.rs
src/lib.rs
src/macros.rs
src/node.rs
src/object.rs
src/text.rs

Also renamed other types:
NodeInfo -> Node
NodeTransform -> Transform

Get rid of Node and NodePointer types

---

src/audio.rs

Temporary fix for #139. We must remember to change the function to `default_endpoints` when the next `rodio` version is released.

Silence deprecated warning for get_default_endpoints

---

src/controls/first_person.rs
src/input/mod.rs

Fixes unwanted 'jagged' input behaviour. This most notably affects the first person camera controls.
Frame | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Event | - | P | - | - | - | P | P | R | - | -
Move | N | Y | N | N | N | Y | Y | N | N | N
Frame | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Event | - | P | - | - | - | P | P | R | - | -
Move | N | Y | Y | Y | Y | Y | Y | N | N | N

 Make key axis deltas continuous instead of discrete 

---

README.md

Fixes #146
I opted to use the fully-qualified URL (including the commit hash) for the image, which should ensure that the link stays valid even if the image is moved or deleted in a later commit.

Fix URL for car screenshot in README.md

---

Cargo.toml
data/shaders/basic_ps.glsl
data/shaders/basic_vs.glsl
data/shaders/gouraud_vs.glsl
data/shaders/locals.glsl
data/shaders/pbr_ps.glsl
data/shaders/pbr_vs.glsl
data/shaders/phong_ps.glsl
data/shaders/phong_vs.glsl
data/shaders/shadow_vs.glsl
data/shaders/sprite_vs.glsl
examples/anim.rs
examples/group.rs
rustfmt.toml
src/animation.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/hub.rs
src/lib.rs
src/material.rs
src/mesh.rs
src/render/mod.rs
src/render/pso_data.rs
src/texture.rs
src/util.rs

fixes #37 
Q&A:
No, just auto instancing support. *(I'm lying, it's crazy)*
Short list:
- All shaders were modified - no more `Locals`, just vertex attributes.
- ~~`Material` enum was renamed to `MaterialType`, made private, added new `Material` struct.
Why? Because I need UIDs to group meshes in renderer.~~
- Huge refactoring in the `render` module in order to reduce code duplication for both instanced and regular rendering.
- ~~`mesh_instance*` was renamed to `duplicate_mesh*`. Reason - you can't change material for mesh with instancing support. (Well, actually you can, but you will lose optimization. Perhaps I should keep this method?)~~
Totally! In group example, performance have increased from 14 to stable 60 FPS (in release mode).
Some things looks really weird, so ask me please. …

Auto instancing

---

src/render/mod.rs

It's not trivial to make it adjustable by window builder settings, so is it okay to enable it by default?

Enable multisampling support for Rasterizer

---

Cargo.toml
examples/anim.rs
examples/aviator/main.rs
examples/aviator/plane.rs
examples/aviator/sky.rs
examples/gltf-animation.rs
examples/gltf.rs
examples/group.rs
examples/lights.rs
examples/materials.rs
examples/mesh-update.rs
examples/obj.rs
examples/reload.rs
examples/shapes.rs
examples/sprite.rs
examples/tutorial.rs
src/animation.rs
src/camera.rs
src/controls/orbit.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/hub.rs
src/lib.rs
src/node.rs
src/object.rs
src/render/mod.rs
src/scene.rs
src/text.rs

Fixes #44
Core of the change is switching relationships from "child->parent" to "parent->first_child->sibling", which gives us the following benefits:
- clean children lifetimes, as expected by users
- no need to store all the meshes returned by gltf/obj loaders: perhaps, we can follow-up with a PR that allows querying meshes by name from their parents, so that we don't even return all the meshes directly in the loader API
- nice `Group::add(&something)`, like Three-js does
- make `Scene` truly unique and node-less
- no need for unique scene IDs
~~- technically, objects can now be present in multiple scenes at once~~
- immutable node data upon traversal (!):
- we just compute the world visibility/transform on the fly
- thus, no need for a separate `update_transforms` step
- uses pretty …

Node tree rewrite

---

src/lib.rs
src/window.rs

Glutin/winit already supports grabbing the cursor, so I've added a new function `Window::set_cursor_state` that directly exposes the glutin/winit API. I've also re-exposed `glutin::CursorState`, in order to make it easy to use `set_cursor_state`.
I've tested this behavior on Windows and it seems to work as I'd expect, but it would be good to test it on Linux and MacOS, as well. There are a few open issues for winit related to cursor handling, but none that seem like they would drastically impact this functionality.

Add support for grabbing cursor

---

src/input/mod.rs

You can notice invalid behavior in `sprite` and `lights` examples before this change.

Fix Delta implementation for axis::Key

---

src/factory/mod.rs

I noticed that these were missing, and they seemed reasonable to add. Let me know if there's any reason we wouldn't want `Gltf` to be `Debug` or `Clone`.

Derive Debug and Clone impls for Gltf

---

src/controls/mod.rs
src/input/mod.rs
src/lib.rs

`MouseButton` wasn't being re-exported, which meant that using it required pulling in glutin or winit as a dependency. I've re-exported it from three so it can be used more easily.

Export MouseButton

---

src/factory/mod.rs

having this as a convenience method would be useful to me, so i added it. look ok?

add `load_texture_with_sampler` method

---

src/input/mod.rs

closes #187 
The behavior of `sprite` and `lights` examples is changed slightly (now you can't hold the key), but I think now it's more logical

Don't count keys hits while key is pressed

---

src/controls/orbit.rs

This means we can have a default sensible position for the camera which the user can then modify but easily revert to the sensible value again.

Add reset() method to Orbit

---

src/hub.rs
src/node.rs
src/object.rs
src/scene.rs

This PR adds the ability to set the name of `Object` types, and retrieve those names when using `SyncGuard` to query the current state of an object.
* Add new member `name: Option<String>` to `NodeInternal` and `Node`.
* Add new trait method `Object::set_name` to allow users to set the name of an object.
This is something that has been discussed in relation to the new template functionality I'm adding in #203. In discussing it with @kvark, he stated that he'd like nodes to be named directly, rather than attempting to have to look up nodes based on their names in a template.

Add node names

---

.gitignore
examples/gltf-morph-targets.rs
examples/gltf-node-animation.rs
examples/gltf-pbr-shader.rs
examples/gltf-vertex-skinning.rs
src/controls/orbit.rs
src/factory/load_gltf.rs
src/factory/mod.rs
src/lib.rs
src/mesh.rs
src/node.rs
src/skeleton.rs
src/template.rs

This PR adds a new system for creating templates for hierarchies of objects. Templates describe many objects and their relationships to each other, and allow the user to instantiate the entire hierarchy of objects at once. Templates can be instantiated an arbitrary number of times. All instances of a template will use the same GPU resources for each instance of a mesh, reducing duplication of GPU resources and allowing for efficient instanced rendering.
* Adds a new module `template` with type declarations for `Template` and its various sub-objects.
* Adds `Factory::instantiate_template` for creating concrete objects from a template.
* Adds `Factory::instanced_geometry` to allow users to upload a `Geometry` to the GPU (this is needed to allow templates to reuse GPU resources).
* Removes …

Template System and Reworked glTF Handling

---

examples/gltf-pbr-shader.rs
src/audio.rs
src/camera.rs
src/factory/load_gltf.rs
src/hub.rs
src/lib.rs
src/light.rs
src/macros.rs
src/mesh.rs
src/node.rs
src/object.rs
src/render/mod.rs
src/scene.rs
src/skeleton.rs
src/sprite.rs
src/text.rs

This PR increases the utility of `SyncGuard` by increasing the information that it can be used to retrieve. In addition to retrieving the `Node` data for any object, it is now possible to:
* Downcast a `Base` to its concrete object type.
* Retrieve internal state data for various object types (e.g. the list of children for `Group`, the projection for `Camera`, etc.).
* Walk the hierarchy of objects under a `Group`.
* Search the hierarchy of objects under a `Group` for specific objects based on their name or type.
This functionality is especially important in conjunction with the `Template` functionality added in #203, as this now allows users to retrieve the objects in a template instance, which drastically increases the utility of templates to create re-usable object hierarchies.
* Adds …

Resolve internal object data with SyncGuard

---

src/object.rs

`Object::look_at` resets the scale of the object to 1. This PR makes it not do that.
This can be demonstrated with a small snippet: https://gist.github.com/LPGhatguy/dc9b4323b3ce7ca950ae936b95038acd
With the correct behavior, the sphere should fill the screen vertically. In 0.3.1 as well as the current master, however, the sphere's scale is reset to 1.0 and no longer fills the screen after `look_at`.

Preserve existing scale in Object::look_at

---

.travis.yml
Cargo.toml
src/factory/mod.rs
src/hub.rs
src/lib.rs
src/object.rs

This reduces the amount of dependencies of 16 if audio support isn’t required by the game.

Make audio support optional
